name: test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build native test lib
        uses: gradle/gradle-build-action@2.4.2
        with:
          arguments: :native:build
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test